name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build:
    uses: tst-race/ext-build-action/.github/workflows/build-ext.yml@v1
    with:
      skip-android-x86_64: true
      skip-android-arm64-v8a: true
